#!/usr/bin/expect -f

set ::env(AMARO_EXPECT) 1
spawn ruby tiramisu

set send_human {.2 .3 .7 .2 2}

expect ".*New project name: "
send -h "AmaroTest\r"

expect -re "Class prefix .*: "
send -h "AMT\r"

expect -re "Your name .*: "
send -h "\r"

expect -re "Organization name .*: "
send -h "Test Corp.\r"

expect -re "Bundle ID domain .*: "
send -h "org.testcorp\r"

sleep 3

expect -re "Would you like to edit .*? "
send -h "n\r"

set timeout 500

expect -re "Would you like to set up .*? "
send -h "n\r"

expect -re "Would you like to open *? "
send -h "n\r"
