#!/usr/bin/expect -f

spawn bash tiramisu.sh

stty echo
set send_human {.2 .3 .7 .2 2}

expect "New project name: "
send -h "AmaroTest\r"

expect -re "Class prefix .*: "
send -h "AMT\r"

expect -re "Your name .*: "
send -h "\r"

expect -re "Organization name .*: "
send -h "Test Corp.\r"

expect -re "Bundle ID domain .*: "
send -h "org.testcorp\r"

sleep 3

expect -re "Would you like to edit .*? "
send -h "n"

set timeout 500

expect -re "Would you like to set up .*? "
send -h "n"

expect -re "Would you like to open *? "
send -h "n"
